version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm install jest --save-dev
            - run: npm run build
            - run: npm run test
      - codecov/upload:
          file: "./coverage/clover.xml"
          token: bc55e615-594b-40a3-bf51-3e408a8e5f85
workflows:
  build-and-test:
    jobs:
      - build-and-test
